spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
multitenancy:
  mtapp:
    dataSources:
      - tenantId: tenant_1
        url: jdbc:mysql://localhost:3306/dbtenant1?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
      - tenantId: tenant_2
        url: jdbc:mysql://localhost:3306/dbtenant2?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
